workspace = { members = ["common", "frontend","backend"] }
[package]
name = "spa-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path="common"}
[lib]
name = "common"
path = "common"
